# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0002_auto_20160611_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twenty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_rating', models.IntegerField()),
                ('average_rating', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieratings.Movie')),
            ],
        ),
    ]
