# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 17:33
from __future__ import unicode_literals
from django.db import migrations
from django.db.models import Avg, Count
from movieratings.models import Twenty


def add_avg_rating(apps, schema_editor):
    Movie = apps.get_model('movieratings', 'Movie')
    Rating = apps.get_model('movieratings', "Rating")

    movies = Movie.objects.all()

    for movie in movies:
        avg_rating_dict = Rating.objects.filter(item_id=movie).values('rating').aggregate(average_rating=Avg("rating"))
        avg_rating = avg_rating_dict.get('average_rating')

        count_rating_dict = Rating.objects.filter(item_id=movie).values('rating').aggregate(count_rating=Count('rating'))
        count_rating = count_rating_dict.get('count_rating')

        Twenty.objects.create(movie=movie,count_ratings=count_rating,average_rating=avg_rating)

    raise Exception("boom")


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0003_twenty'),
    ]

    operations = [
        migrations.RunPython(add_avg_rating)
    ]
