# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:24
from __future__ import unicode_literals
from django.db import migrations
from django.db.models import Avg, Count


def avg_rating(apps, schema_editor):
    Movie = apps.get_model('movieratings', 'Movie')
    Rating = apps.get_model('movieratings', "Rating")
    AverageRating = apps.get_model('movieratings', 'AverageRating')

    movies = Movie.objects.all()

    for movie in movies:

        avg_rating_dict = Rating.objects.filter(item=movie.id).values('rating').aggregate(average_rating=Avg("rating"))

        avg_rating = avg_rating_dict.get('average_rating')

        count_rating_dict = Rating.objects.filter(item=movie.id).values('rating').aggregate(count_rating=Count('rating'))

        count_rating = count_rating_dict.get('count_rating')

        if count_rating > 20:
            avg_rating = avg_rating
        else:
            avg_rating = 0

        # print(movie.title, avg_rating, count_rating)

        AverageRating.objects.create(movie=movie, count_ratings=count_rating, average_rating=avg_rating)

    # raise Exception("boom")


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0003_averagerating'),
    ]

    operations = [
        migrations.RunPython(avg_rating)
    ]
